version: "3"
services:
  fabric-bot:
    image: ghcr.io/fabricmc/fabric-discord-bot:latest
    container_name: fabric-bot

    depends_on:
      - fabric-bot-db

    restart: always

    volumes:
      - /home/docker/volumes/bot:/data

    environment:
      - BOT_PREFIX=?
      - DB_URL=mysql://fabric-bot-db/fabric_bot
      - DB_USERNAME=fabric_bot
      - ENVIRONMENT=production
      - SENTRY_ENVIRONMENT=production

      - BOT_TOKEN
      - DB_PASSWORD
      - GITHUB_ORG
      - GITHUB_TOKEN
      - SENTRY_DSN

  fabric-bot-db:
    image: mariadb:10
    container_name: fabric-bot-db

    command: --default-authentication-plugin=mysql_native_password
    restart: always

    volumes:
      - /home/docker/volumes/bot/mariadb:/var/lib/mysql

    environment:
      - MYSQL_DATABASE=fabric_bot
      - MYSQL_USER=fabric_bot
      - MYSQL_PASSWORD=${DB_PASSWORD?:err}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD?:err}
